context:
  name: rainfrog
  version: "0.3.0"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://github.com/achristmascarl/${{ name }}/archive/refs/tags/v${{ version }}.tar.gz
  sha256: e99dfbdce5a5b5c051dbaec49351e475ebd89a121534e91291b9907dcae57de2

build:
  script:
    - cargo-bundle-licenses --format yaml --output THIRDPARTY.yml
    - cargo install --no-track --locked --root ${{ PREFIX }} --path .

  number: 0

requirements:
  build:
    - ${{ compiler('rust') }}
    - ${{ compiler('c') }}
    - ${{ stdlib('c') }}
    - cargo-bundle-licenses

tests:
  - script:
      - rainfrog --version

about:
  homepage: https://crates.io/crates/rainfrog
  summary: '🐸 a database management tui for postgres'
  description: |
    The goal for rainfrog is to provide a lightweight, terminal-based alternative to pgadmin/dbeaver.
  license: MIT
  license_file:
    - LICENSE
    - THIRDPARTY.yml
  repository: https://github.com/achristmascarl/rainfrog/

extra:
  recipe-maintainers:
    - achristmascarl
    - eunos-1128
