context:
  name: rainfrog
  version: "0.3.7"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://github.com/achristmascarl/${{ name }}/archive/refs/tags/v${{ version }}.tar.gz
  sha256: 7e6457c9041b2b28bd77324e76210bf1ff8f23b58ff6980d9bccc142286af091

build:
  number: 0
  script:
    - cargo-bundle-licenses --format yaml --output THIRDPARTY.yml
    - if: linux and ppc64le
      # The libduckdb-sys crate not appear to support the powerpc64le architecture
      then: cargo install --no-track --locked --root ${{ PREFIX }} --path . --no-default-features --features "musl"
      else: cargo install --no-track --locked --root ${{ PREFIX }} --path .

requirements:
  build:
    - ${{ compiler('c') }}
    - ${{ compiler('cxx') }}
    - ${{ compiler('rust') }}
    - ${{ stdlib('c') }}
    - cargo-bundle-licenses
    - if: build_platform != target_platform
      then: libiconv

tests:
  - script:
      - rainfrog --version

about:
  homepage: https://crates.io/crates/rainfrog
  summary: '🐸 a database management tui for postgres'
  description: |
    The goal for rainfrog is to provide a lightweight, terminal-based alternative to pgadmin/dbeaver.
  license: MIT
  license_file:
    - LICENSE
    - THIRDPARTY.yml
  repository: https://github.com/achristmascarl/rainfrog/

extra:
  recipe-maintainers:
    - achristmascarl
    - eunos-1128
